Vagrant.configure("2") do |c|
        c.ssh.insert_key = true
        c.vm.define 'ubuntu-1604-x64' do |v|
                v.vm.hostname = 'ubuntu-1604-x64'
                v.vm.box = 'ubuntu/xenial64'
                v.vm.box_url = 'https://atlas.hashicorp.com/ubuntu/boxes/xenial64'
                v.vm.box_check_update = 'true'
                v.vm.network :private_network, ip: "10.255.201.160", :netmask => "255.255.0.0", :mac => "080027606481"
                v.vm.provider :virtualbox do |vb|
                        vb.customize ['modifyvm', :id, '--memory', '1024', '--cpus', '1']
                        vb.gui = true
                end


                c.vm.synced_folder "Project", "/home/ubuntu/dotfiles", type: "rsync", rsync__exclude: [ ".git/", "vagrantfiles"]
                c.vm.provision "shell", inline:"locale-gen de_DE.UTF-8"
                c.vm.provision "shell", inline:"echo ubuntu:ubuntu | chpasswd"
                #c.vm.provision "shell", run: "never" do |s|
                #        s.path = "/home/vagrant/dotfiles/install.sh,"
                #        s.privileged =  false
                #end


        end
end

