#!/bin/sh
lock() {
	~/.config/i3/i3lock-fancy/lock&
}

case "$1" in
    lock)
	    lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
lock && sleep 2 && sudo s2ram
        ;;
    hibernate)
        lock && sleep 2 && sudo s2disk
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
